services:
  - type: web
    name: physioflexstudio
    env: node
    buildCommand: npm run build
    startCommand: node .output/server/index.mjs
    publishDirectory: .output
    plan: free
    envVars:
      - key: NITRO_PRESET
        value: node-server
