/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecialistsIndexRouteImport } from './routes/specialists.index'
import { Route as SpecialistsIdRouteImport } from './routes/specialists.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistsIndexRoute = SpecialistsIndexRouteImport.update({
  id: '/specialists/',
  path: '/specialists/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistsIdRoute = SpecialistsIdRouteImport.update({
  id: '/specialists/$id',
  path: '/specialists/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/booking': typeof BookingRoute
  '/dashboard': typeof DashboardRoute
  '/recovery': typeof RecoveryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialists/$id': typeof SpecialistsIdRoute
  '/specialists/': typeof SpecialistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/booking': typeof BookingRoute
  '/dashboard': typeof DashboardRoute
  '/recovery': typeof RecoveryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialists/$id': typeof SpecialistsIdRoute
  '/specialists': typeof SpecialistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/booking': typeof BookingRoute
  '/dashboard': typeof DashboardRoute
  '/recovery': typeof RecoveryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialists/$id': typeof SpecialistsIdRoute
  '/specialists/': typeof SpecialistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/booking'
    | '/dashboard'
    | '/recovery'
    | '/sitemap.xml'
    | '/specialists/$id'
    | '/specialists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/booking'
    | '/dashboard'
    | '/recovery'
    | '/sitemap.xml'
    | '/specialists/$id'
    | '/specialists'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/booking'
    | '/dashboard'
    | '/recovery'
    | '/sitemap.xml'
    | '/specialists/$id'
    | '/specialists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  BookingRoute: typeof BookingRoute
  DashboardRoute: typeof DashboardRoute
  RecoveryRoute: typeof RecoveryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpecialistsIdRoute: typeof SpecialistsIdRoute
  SpecialistsIndexRoute: typeof SpecialistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialists/': {
      id: '/specialists/'
      path: '/specialists'
      fullPath: '/specialists/'
      preLoaderRoute: typeof SpecialistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialists/$id': {
      id: '/specialists/$id'
      path: '/specialists/$id'
      fullPath: '/specialists/$id'
      preLoaderRoute: typeof SpecialistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  BookingRoute: BookingRoute,
  DashboardRoute: DashboardRoute,
  RecoveryRoute: RecoveryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpecialistsIdRoute: SpecialistsIdRoute,
  SpecialistsIndexRoute: SpecialistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
